//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Tab2
    {
        public int App_Id { get; set; }
        public int User_Id { get; set; }
        public int Com_Id { get; set; }
        public int Job_Id { get; set; }
        public string CV { get; set; }
        public string App_Date { get; set; }
        public string Status { get; set; }
    }
}
