//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyReg_Tab1
    {
        public int Comp_Id { get; set; }
        public string Comp_Name { get; set; }
        public string Comp_Address { get; set; }
        public string Comp_Phone { get; set; }
        public string Comp_website { get; set; }
        public string Comp_Email { get; set; }
        public string Comp_Location { get; set; }
    }
}
