//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Tab1
    {
        public int Job_Id { get; set; }
        public int Comp_Id { get; set; }
        public string Job_Tittle { get; set; }
        public int Job_Experi { get; set; }
        public string job_Skills { get; set; }
        public int No_Vacc { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    }
}
