//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReg_Tab1
    {
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public int User_Age { get; set; }
        public string User_Address { get; set; }
        public string User_Email { get; set; }
        public string User_Phone { get; set; }
        public string User_Photo { get; set; }
        public string User_Qual { get; set; }
        public int User_Expe { get; set; }
        public string User_Skills { get; set; }
        public string User_Resume { get; set; }
    }
}
